/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import controller.ServerController;
import domain.Kviz;
import domain.Pitanje;
import java.util.List;
import javax.swing.JOptionPane;
import thread.ThreadServer;

/**
 *
 * @author Rastko
 */
public class Form extends javax.swing.JDialog {

    /**
     * Creates new form Form
     */
    private Pitanje trenutnoPitanje;
    public Form(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        txtPitanje.setEditable(false);
        popuniCmb();
        btnPosaljiOdgovor.setEnabled(false);
        txtPoruka.setEditable(false);
        txtUkupnoPoena.setEditable(false);
        tblRezultati.setModel(ServerController.getInstance().getTableModel());
        ThreadServer threadServer=new ThreadServer();
        threadServer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbKvizovi = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnPokreniKviz = new javax.swing.JButton();
        txtPitanje = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOdgovor = new javax.swing.JTextField();
        btnPosaljiOdgovor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPoruka = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUkupnoPoena = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRezultati = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kviz");

        jLabel2.setText("Pitanje");

        btnPokreniKviz.setText("Pokreni kviz");
        btnPokreniKviz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniKvizActionPerformed(evt);
            }
        });

        jLabel3.setText("Odgovor");

        btnPosaljiOdgovor.setText("Posalji odgovor");
        btnPosaljiOdgovor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosaljiOdgovorActionPerformed(evt);
            }
        });

        jLabel4.setText("Poruka");

        jLabel5.setText("Ukupno poena");

        tblRezultati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRezultati);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtPitanje))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOdgovor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPokreniKviz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPosaljiOdgovor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtPoruka))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUkupnoPoena))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbKvizovi, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbKvizovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPokreniKviz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPitanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtOdgovor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPosaljiOdgovor)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUkupnoPoena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPokreniKvizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniKvizActionPerformed
        Kviz izabraniKviz=(Kviz)cmbKvizovi.getSelectedItem();
        ServerController.getInstance().setKviz(izabraniKviz);
        btnPokreniKviz.setEnabled(false);
        ThreadForm th=new ThreadForm(this);
        th.start();
    }//GEN-LAST:event_btnPokreniKvizActionPerformed

    private void btnPosaljiOdgovorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosaljiOdgovorActionPerformed
        String textOdg= txtOdgovor.getText();
        Pitanje odgovor=new Pitanje(trenutnoPitanje.getPitanjeId(), trenutnoPitanje.getPitanje(), textOdg, trenutnoPitanje.getBrojPoena());
        String poruka=ServerController.getInstance().posaljiOdgovor(odgovor, "server");
        txtPoruka.setText(poruka);
    }//GEN-LAST:event_btnPosaljiOdgovorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form dialog = new Form(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPokreniKviz;
    private javax.swing.JButton btnPosaljiOdgovor;
    private javax.swing.JComboBox<Object> cmbKvizovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRezultati;
    private javax.swing.JTextField txtOdgovor;
    private javax.swing.JTextField txtPitanje;
    private javax.swing.JTextField txtPoruka;
    private javax.swing.JTextField txtUkupnoPoena;
    // End of variables declaration//GEN-END:variables

    private void popuniCmb() {
        List<Kviz> kvizovi=ServerController.getInstance().getAllKvizovi();
        cmbKvizovi.removeAllItems();
        for(Kviz kviz:kvizovi)
            cmbKvizovi.addItem(kviz);
    }

    public Pitanje getTrenutnoPitanje() {
        return trenutnoPitanje;
    }

    public void setTrenutnoPitanje(Pitanje trenutnoPitanje) {
        this.trenutnoPitanje = trenutnoPitanje;
        txtPitanje.setText(trenutnoPitanje.getPitanje());
    }
    public void krajIgre(String poruka){
        JOptionPane.showMessageDialog(this, "Kraj igre: "+poruka);
        this.dispose();
    }
    public void enablePosaljiOdgovorButton(){
        btnPosaljiOdgovor.setEnabled(true);
    }
    
    public void setBrojPoena(){
        txtUkupnoPoena.setText(Double.toString(ServerController.getInstance().getBrojBodovaServer()));
    }
}
